### ISSUE TITLE
Repository Contributors

### ISSUE THREAD

**Issue by rafaelcorsi** [NSEE/SimuCam_Development#31]
Andei dando uma zapiada pelo repo e me senti excluído do projeto :cry: :cry:.

Se puderem me colocar:

```
- [Rafael Corsi Ferrão - Hardware Engineer](https://github.com/rafaelcorsi) (2011-2017) 
```

Alias, parabéns pelo resultado o projeto é um uma obra prima!

abs,

Corsi

**Comment by ericolucasm** [comment]
Done, @rafaelcorsi .
